name: Homebridge
version: "0.2.0"
slug: homebridge
description: Run Homebridge in the Home Assistant sidebar using ingress
url: "https://github.com/rohanod/ha-addon-homebridge/tree/main/homebridge"
stage: stable
panel_admin: true
panel_title: Homebridge
panel_icon: mdi:bridge
arch:
  - amd64
  - aarch64
  - armv7
init: false
legacy: true
host_network: true
startup: application
boot: auto
ingress: true
ingress_port: 8099
watchdog: "http://[HOST]:[PORT:8581]"
map:
  - type: data
    path: /homebridge
schema: false
